version: "3.0"
services:
  db:
    image: mysql:8.0
    container_name: mysql-quiz-game
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: quiz_game
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
    my-db: