version: "3.0"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: game
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
    db:
      driver: local